[package]
name = "detectors-rs"
version = "0.2.0"
authors = ["brownie"]
edition = "2018"

[dependencies]
GSL = "*"
nalgebra = "*"
ndarray = "0.11.2"
optimize = "*"
rand = "*"
rayon = "*"
serde = "*"
structopt = "*"
serde_json = "*"
serde_derive = "*"
val_unc = { git = "https://github.com/j-browne/val_unc" }
