[package]
name = "detectors-rs"
version = "0.1.0"
authors = ["brownie"]
edition = "2018"

[dependencies]
GSL = "*"
nalgebra = "*"
ndarray = "*"
optimize = "*"
rayon = "*"
ron = "*"
serde = "*"
structopt = "*"
