[package]
name = "detectors-rs"
version = "0.1.0"
authors = ["brownie"]
edition = "2018"

[dependencies]
nalgebra = "*"
GSL = "*"
serde = "*"
serde_derive = "*"
serde_json = "*"
rayon = "*"
structopt = "*"
