[package]
name = "detectors-rs"
version = "0.1.0"
authors = ["brownie"]
edition = "2018"

[dependencies]
GSL = "*"
nalgebra = "*"
ndarray = "0.11.2"
optimize = "*"
rand = "*"
rayon = "*"
serde = "*"
structopt = "*"
serde_json = "*"
serde_derive = "*"
val_unc = { path = "../val_unc" }
